const swaggerAutogen = require('swagger-autogen')();
const path = require('path');

const outputFile = path.join(__dirname, './swagger-output.json');
// Point to the root file that imports all your routes
const endpointsFiles = [path.join(__dirname, './server.js')]; 

const doc = {
  info: {
    title: 'My API (DataDox)',
    description: 'Documentation generated by swagger-autogen.',
  },
  host: 'localhost:3000', // Adjust port if necessary
  schemes: ['http'],
};

swaggerAutogen(outputFile, endpointsFiles, doc);
